spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: '395654748851809'
            client-secret: 4d7a5ed57b66727220056330b369e9ee
          github:
            client-id: 953e0f21abfa0c2eee61
            client-secret: 42ec454dd0c196ddad7b468e3452d9259b25386e
          google:
            client-id: 450982459846-die6mu5a8nn7d0go8c4invio7l3a5puu.apps.googleusercontent.com
            client-secret: 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
          github-openapi:
            client-id: 45fadf2a64afffa40c6d
            client-secret: 35952c4e33dc60eb9f6af54653ab5a5f91adc96e
            scope:
              - read:user
              - user:email
            redirect-uri: http://localhost:8080/swagger-ui/oauth2-redirect.html
            client-name: github-openapi
            provider: github-openapi
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
        provider:
          github-openapi:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
            user-info-authentication-method: header
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/sleep_tracker

oauth2:
  client:
    google:
      redirectUri: http://localhost:8080/login/oauth2/code/google
      scope: profile email
    facebook:
      redirectUri: http://localhost:8080/login/oauth2/code/facebook
      scope: email,public_profile
    github:
      redirectUri: http://localhost:8080/login/oauth2/code/github
      scope: user:email read:user
